In [1]:
import pandas as pd
import numpy as np

from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4], index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
#this will create a dataframe
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [12]:
#add keys to the concat result
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [16]:
dframe1

X         Y         Z
0 -0.544864  0.587640  0.681617
1  0.861624  1.211707 -1.498996
2  1.223884 -0.468189  0.186029
3  1.759619 -1.206576  0.054333

In [17]:
dframe2

Y         Q         X
0  1.294792  1.086113 -2.343612
1  1.163780  0.250814 -0.840021
2 -1.058027 -0.242277 -1.616923

In [18]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.544864  0.587640  0.681617
1       NaN  0.861624  1.211707 -1.498996
2       NaN  1.223884 -0.468189  0.186029
3       NaN  1.759619 -1.206576  0.054333
0  1.086113 -2.343612  1.294792       NaN
1  0.250814 -0.840021  1.163780       NaN
2 -0.242277 -1.616923 -1.058027       NaN

In [19]:
#we can also get rid of index information
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.544864  0.587640  0.681617
1       NaN  0.861624  1.211707 -1.498996
2       NaN  1.223884 -0.468189  0.186029
3       NaN  1.759619 -1.206576  0.054333
4  1.086113 -2.343612  1.294792       NaN
5  0.250814 -0.840021  1.163780       NaN
6 -0.242277 -1.616923 -1.058027       NaN