In [2]:
# DAta analysis is array and matrix basied. 

In [3]:
import numpy as np

In [4]:
myList1 = [1,2,3,4]

In [5]:
myArray1 = np.array(myList1)

In [6]:
myArray1

array([1, 2, 3, 4])

In [7]:
myList2 = [11,22,33,44]

In [8]:
myLists = [myList1,myList2]

In [10]:
myLists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [11]:
myArray2 = np.array(myLists)

In [12]:
myArray2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [14]:
#look at the shape
myArray2.shape

(2L, 4L)

In [15]:
#ge tthe data type
myArray2.dtype

dtype('int32')

In [16]:
#create an array of zeros
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
myZerosArray = np.zeros(5)

In [18]:
myZerosArray.dtype

dtype('float64')

In [20]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
#identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])