In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
a = np.random.randn(10)
a

array([-0.35675311,  1.33441102,  1.27590077,  0.79006635, -0.46913465,
        1.75379688,  0.61954394, -1.90022332, -0.21321949,  0.47322445])

In [6]:
b = np.random.randn(10)
b

array([ 0.35999841, -0.68272806,  0.1774616 ,  0.93577393, -0.11159171,
        0.9092267 , -1.57484237,  1.51350293, -1.21639116, -1.08252955])

In [7]:
#binary functions
np.add(a,b)

array([ 0.00324529,  0.65168296,  1.45336237,  1.72584028, -0.58072636,
        2.66302359, -0.95529843, -0.38672039, -1.42961065, -0.6093051 ])

In [8]:
np.maximum(a,b)

array([ 0.35999841,  1.33441102,  1.27590077,  0.93577393, -0.11159171,
        1.75379688,  0.61954394,  1.51350293, -0.21321949,  0.47322445])

In [9]:
import webbrowser
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
webbrowser.open(website)

True